version: '3'
services:
  realty_db:
    image: postgres:14
    restart: always
    env_file:
      - '.env'
    volumes:
      - /opt/postgres/realty_tg_bot:/var/lib/postgresql/data/
    ports:
      - '5532:5432'
    networks:
      - realty_db_network

  realty_bot:
    build:
      context: .
    restart: always
    command: python3 bot.py
    env_file:
      - '.env'
    volumes:
      - .:/realty_tg_bot
#      - ./realty_tg_bot/logs:/var/logs
    depends_on:
      - realty_db
      - realty_web
      - realty_redis
      - realty_grafana
      - realty_influxdb
    networks:
      - realty_db_network

  realty_web:
    build:
      context: .
    image: realty_web
    restart: always
    command: ./run_web.sh
    env_file:
      - '.env'
    volumes:
      - .:/realty_tg_bot
    depends_on:
      - realty_db
    ports:
      - '8900:8000'
    networks:
      - realty_db_network

  realty_redis:
    image: redis:7.0.2
    restart: always
    ports:
      - '6479:6379'
    command: redis-server
    volumes:
      - /var/lib/redis:/var/lib/redis
      - ./redis.conf:/var/lib/redis/redis.conf
    networks:
      - realty_db_network

  realty_influxdb:
    image: influxdb:latest
    restart: always
    volumes:
      - /opt/influxdb/realty_tg_bot:/var/lib/influxdb2
#      - /opt/influxdb/realty_tg_bot:/etc/influxdb2
    env_file:
      - '.env'
    ports:
      - '8186:8086'
    networks:
      - realty_db_network

  realty_grafana:
    image: grafana/grafana
    environment:
      - GF_DATE_FORMATS_DEFAULT_TIMEZONE=browser
    ports:
      - '3100:3000'
    networks:
      - realty_db_network

networks:
  realty_db_network:
    driver: bridge
