version: '3'
services:
  realty_db:
    image: postgres:14
    restart: always
    env_file:
      - '.env'
    volumes:
      - /opt/postgres/realty_bot:/var/lib/postgresql/data/
    ports:
      - '5459:5432'
    networks:
      - realty_db_network

  realty_bot:
    build:
      context: .
    restart: always
    command: python3 bot.py
    env_file:
      - '.env'
    volumes:
      - .:/realty_tg_bot
#      - ./telegram_bot/logs:/var/logs
    depends_on:
      - realty_db
      - realty_web
      - redis
    networks:
      - realty_db_network

  realty_web:
    build:
      context: .
    image: realty_web
    restart: always
    command: ./run_web.sh
    env_file:
      - '.env'
    volumes:
      - .:/realty_tg_bot
    depends_on:
      - realty_db
    ports:
      - '8383:8000'
    networks:
      - realty_db_network

  redis:
    image: redis:7.0.2
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - /var/lib/redis:/var/lib/redis
      - ./redis.conf:/var/lib/redis/redis.conf
    networks:
      - realty_db_network


networks:
  realty_db_network:
    driver: bridge
