version: '3'
services:
  turgenev_realty_db:
    image: postgres:14
    restart: always
    env_file:
      - '.env'
    volumes:
      - /opt/postgres/turgenev_realty_bot:/var/lib/postgresql/data/
    ports:
      - '5484:5432'
    networks:
      - turgenev_realty_db_network

  turgenev_realty_bot:
    build:
      context: .
    restart: always
    command: python3 bot.py
    env_file:
      - '.env'
    volumes:
      - .:/turgenev_realty_bot
#      - ./turgenev_realty_bot/logs:/var/logs
    depends_on:
      - turgenev_realty_db
      - turgenev_realty_web
      - turgenev_realty_redis
      - turgenev_realty_grafana
      - turgenev_realty_influxdb
    networks:
      - turgenev_realty_db_network

  turgenev_realty_web:
    build:
      context: .
    image: turgenev_realty_web
    restart: always
    command: ./run_web.sh
    env_file:
      - '.env'
    volumes:
      - .:/turgenev_realty_bot
    depends_on:
      - turgenev_realty_db
    ports:
      - '8408:8000'
    networks:
      - turgenev_realty_db_network

  turgenev_realty_redis:
    image: redis:7.0.2
    restart: always
    ports:
      - '6404:6379'
    command: redis-server
    volumes:
      - /var/lib/redis:/var/lib/redis
      - ./redis.conf:/var/lib/redis/redis.conf
    networks:
      - turgenev_realty_db_network

  turgenev_realty_influxdb:
    image: influxdb:latest
    restart: always
    volumes:
      - /opt/influxdb/turgenev_realty_bot:/var/lib/influxdb2
#      - /opt/influxdb/turgenev_realty_bot:/etc/influxdb2
    env_file:
      - '.env'
    ports:
      - '8114:8086'
    networks:
      - turgenev_realty_db_network

  turgenev_realty_grafana:
    image: grafana/grafana
    environment:
      - GF_DATE_FORMATS_DEFAULT_TIMEZONE=browser
    ports:
      - '3034:3000'
    networks:
      - turgenev_realty_db_network

networks:
  turgenev_realty_db_network:
    driver: bridge
